version: '3.8'

services:

  bookmanagement:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bookmanagement
    network_mode: bridge
    environment:
      - SPRING_PROFILES_ACTIVE=test,docker
      - POSTGRES_PASSWORD=Localadm!n123
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - DB_HOSTNAME=postgres
    ports:
      - "8080:8080"
      - "8083:8083"
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Localadm!n123
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    restart: unless-stopped
    volumes:
      - ./mnt/postgresql:/var/lib/postgresql